### ISSUE TITLE
Issue in matter_power_spt.py line 62

### ISSUE THREAD

**Issue by CarterDW** [jablazek/FAST-PT#10]
the Z function in matter_power_spt.py line 62 (P_13_reg function) has 96/.5/r^2, it should be 96/5/r^2 (difference of 0.5 to 5)
@DDeRienzo

**Comment by xfangcosmo** [comment]
This will be corrected in this pull request: [https://github.com/jablazek/FAST-PT/pull/11](https://github.com/jablazek/FAST-PT/pull/11)

**Comment by dderienzo** [comment]
Solved with PR #11
